export const SET_DETAILS = "SET_DETAILS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SET_CART_DATA = "SET_CART_DATA";
export const SET_COMPLETED_CART = "SET_COMPLETED_CART";
export const SET_BUYER_DETAILS = "SET_BUYER_DETAILS";
